### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by myzhang1029** [myzhang1029/psh#1]
- [ ] Replace filpinfo with a tokenizer.
 - [ ] Finish posix backend.
 - [ ] Wirte history save 'n' load.
 - [ ] Write alias pool.
 - [ ] Implement variables.
 - [ ] Implement job control.
 - [ ] Write POSIX/Shell builtins, bash builtins and implement most coreutils as builtins.
 - [ ] Write Windows backend.

**Comment by myzhang1029** [comment]
Moved to GitHub Projects
